/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventory.assignment;

import inventory.assignment.dao.ProductDAO;
import inventory.assignment.dao.SupplierDAO;
import inventory.assignment.repository.ProductRepository;
import inventory.assignment.repository.SupplierRepository;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dungnh
 */
public class MainFrame extends javax.swing.JFrame {

    private ProductRepository productRepository;

    private SupplierRepository supplierRepository;

    private List<String> supplierNames = new ArrayList<>();

    private Map<String, Integer> supplierSelection = new HashMap<>();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        productRepository = new ProductRepository();
        supplierRepository = new SupplierRepository();
        initSupplierSelection();
    }

    private void initSupplierSelection() {
        List<SupplierDAO> suppliers = supplierRepository.getListSupplier();
        for (SupplierDAO s : suppliers) {
            if (s.isIsActive() == false) {
                continue;
            }
            this.supplierNames.add(s.getName());
        }

        for (SupplierDAO s : suppliers) {
            if (s.isIsActive() == false) {
                continue;
            }
            supplierSelection.put(s.getName(), s.getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        productTab = new javax.swing.JPanel();
        productHeaderContainer = new javax.swing.JPanel();
        productSearchTf = new javax.swing.JTextField();
        productSearchBtn = new javax.swing.JButton();
        productAllBtn = new javax.swing.JButton();
        productNewBtn = new javax.swing.JButton();
        productTableContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        productItemContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productIdTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        productSkuTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productNameTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        productPriceTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        productQuantityTf = new javax.swing.JTextField();
        productUpdateBtn = new javax.swing.JButton();
        productRemoveBtn = new javax.swing.JButton();
        productCreateBtn = new javax.swing.JButton();
        productResetBtn = new javax.swing.JButton();
        productCancelBtn = new javax.swing.JButton();
        productSupplierComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productTab.setPreferredSize(new java.awt.Dimension(750, 500));

        productHeaderContainer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        productSearchBtn.setText("Search");
        productSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSearchBtnActionPerformed(evt);
            }
        });

        productAllBtn.setText("All");
        productAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productAllBtnActionPerformed(evt);
            }
        });

        productNewBtn.setText("New");
        productNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productHeaderContainerLayout = new javax.swing.GroupLayout(productHeaderContainer);
        productHeaderContainer.setLayout(productHeaderContainerLayout);
        productHeaderContainerLayout.setHorizontalGroup(
            productHeaderContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productHeaderContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productSearchTf, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productSearchBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productAllBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productNewBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productHeaderContainerLayout.setVerticalGroup(
            productHeaderContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productHeaderContainerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(productHeaderContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productSearchTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productSearchBtn)
                    .addComponent(productAllBtn)
                    .addComponent(productNewBtn))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        productTableContainer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Sku", "Name", "Supplier", "Quantity", "Price"
            }
        ));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        javax.swing.GroupLayout productTableContainerLayout = new javax.swing.GroupLayout(productTableContainer);
        productTableContainer.setLayout(productTableContainerLayout);
        productTableContainerLayout.setHorizontalGroup(
            productTableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTableContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );
        productTableContainerLayout.setVerticalGroup(
            productTableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTableContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        productItemContainer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("ID");

        productIdTf.setEnabled(false);

        jLabel2.setText("Sku");

        jLabel3.setText("Name");

        jLabel4.setText("Supplier");

        jLabel5.setText("Price");

        jLabel6.setText("Quantity");

        productUpdateBtn.setText("Update");
        productUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productUpdateBtnActionPerformed(evt);
            }
        });

        productRemoveBtn.setText("Remove");
        productRemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productRemoveBtnActionPerformed(evt);
            }
        });

        productCreateBtn.setText("Create");
        productCreateBtn.setDefaultCapable(false);
        productCreateBtn.setEnabled(false);
        productCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCreateBtnActionPerformed(evt);
            }
        });

        productResetBtn.setText("Reset");
        productResetBtn.setEnabled(false);
        productResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productResetBtnActionPerformed(evt);
            }
        });

        productCancelBtn.setText("Cancel");
        productCancelBtn.setEnabled(false);
        productCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCancelBtnActionPerformed(evt);
            }
        });

        productSupplierComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSupplierComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productItemContainerLayout = new javax.swing.GroupLayout(productItemContainer);
        productItemContainer.setLayout(productItemContainerLayout);
        productItemContainerLayout.setHorizontalGroup(
            productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productItemContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productItemContainerLayout.createSequentialGroup()
                        .addGroup(productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(productItemContainerLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(productIdTf))
                            .addGroup(productItemContainerLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(productSkuTf, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addGroup(productItemContainerLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(productNameTf, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addGroup(productItemContainerLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(productPriceTf, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addGroup(productItemContainerLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(productQuantityTf, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addGroup(productItemContainerLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(productSupplierComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productItemContainerLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(productItemContainerLayout.createSequentialGroup()
                                .addComponent(productUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(productRemoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(productItemContainerLayout.createSequentialGroup()
                                .addGroup(productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(productResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(productCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        productItemContainerLayout.setVerticalGroup(
            productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productItemContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(productIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productSkuTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(productNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(productSupplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(productPriceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(productQuantityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productUpdateBtn)
                    .addComponent(productRemoveBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productCreateBtn)
                    .addComponent(productCancelBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productResetBtn)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout productTabLayout = new javax.swing.GroupLayout(productTab);
        productTab.setLayout(productTabLayout);
        productTabLayout.setHorizontalGroup(
            productTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(productHeaderContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(productTabLayout.createSequentialGroup()
                .addComponent(productTableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productItemContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        productTabLayout.setVerticalGroup(
            productTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productHeaderContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productItemContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productTableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainTabbedPane.addTab("Product", productTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listAllProduct() {
        List<ProductDAO> products = productRepository.listProduct();
        renderProductTable(products);
    }

    private void productAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productAllBtnActionPerformed
        listAllProduct();
    }//GEN-LAST:event_productAllBtnActionPerformed

    private void productSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSearchBtnActionPerformed
        String searchContent = productSearchTf.getText();
        List<ProductDAO> products = productRepository.searchProduct(searchContent);
        renderProductTable(products);
    }//GEN-LAST:event_productSearchBtnActionPerformed

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        int row = productTable.getSelectedRow();
        productIdTf.setText(model.getValueAt(row, 0).toString());
        productSkuTf.setText(model.getValueAt(row, 1).toString());
        productNameTf.setText(model.getValueAt(row, 2).toString());
        String selectedSupplierName = model.getValueAt(row, 3).toString();
        productQuantityTf.setText(model.getValueAt(row, 4).toString());
        productPriceTf.setText(model.getValueAt(row, 5).toString());

        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel(supplierNames.toArray());
        productSupplierComboBox.setModel(comboBoxModel);
        productSupplierComboBox.setSelectedItem(selectedSupplierName);
    }//GEN-LAST:event_productTableMouseClicked

    private void productUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productUpdateBtnActionPerformed
        int id = Integer.parseInt(productIdTf.getText());
        String name = productNameTf.getText();
        String sku = productSkuTf.getText();
        double price = Double.parseDouble(productPriceTf.getText());
        int qty = Integer.parseInt(productQuantityTf.getText());
        int supplierId = supplierSelection.get(productSupplierComboBox.getSelectedItem().toString());
        ProductDAO p = new ProductDAO(id, sku, name, supplierId, price, qty);
        productRepository.updateProductByID(p);
        listAllProduct();
    }//GEN-LAST:event_productUpdateBtnActionPerformed

    private void productSupplierComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSupplierComboBoxActionPerformed

    }//GEN-LAST:event_productSupplierComboBoxActionPerformed

    private void productRemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productRemoveBtnActionPerformed
        int id = Integer.parseInt(productIdTf.getText());
        productRepository.removeProductByID(id);
        listAllProduct();
    }//GEN-LAST:event_productRemoveBtnActionPerformed

    private void productNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNewBtnActionPerformed
        productUpdateBtn.setEnabled(false);
        productRemoveBtn.setEnabled(false);
        productCreateBtn.setEnabled(true);
        productCancelBtn.setEnabled(true);
        productResetBtn.setEnabled(true);

        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel(supplierNames.toArray());
        productSupplierComboBox.setModel(comboBoxModel);
        productResetBtnActionPerformed(evt);
    }//GEN-LAST:event_productNewBtnActionPerformed

    private void productCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCreateBtnActionPerformed
        String name = productNameTf.getText();
        String sku = productSkuTf.getText();
        double price = Double.parseDouble(productPriceTf.getText());
        int qty = Integer.parseInt(productQuantityTf.getText());
        int supplierId = supplierSelection.get(productSupplierComboBox.getSelectedItem().toString());
        ProductDAO p = new ProductDAO(sku, name, supplierId, price, qty);
        productRepository.createProductByID(p);
        listAllProduct();
        productCancelBtnActionPerformed(evt);
    }//GEN-LAST:event_productCreateBtnActionPerformed

    private void productResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productResetBtnActionPerformed
        productSkuTf.setText("");
        productNameTf.setText("");
        productSupplierComboBox.setSelectedIndex(0);
        productPriceTf.setText("");
        productQuantityTf.setText("");
    }//GEN-LAST:event_productResetBtnActionPerformed

    private void productCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCancelBtnActionPerformed
        productUpdateBtn.setEnabled(true);
        productRemoveBtn.setEnabled(true);
        productCreateBtn.setEnabled(false);
        productCancelBtn.setEnabled(false);
        productResetBtn.setEnabled(false);
        productResetBtnActionPerformed(evt);
    }//GEN-LAST:event_productCancelBtnActionPerformed

    private void renderProductTable(List<ProductDAO> products) {
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        model.setRowCount(0);
        for (ProductDAO product : products) {
            model.addRow(new Object[]{product.getId(), product.getSku(), product.getName(), product.getSupplierName(), product.getQuantity(), product.getPrice()});
        }
        productTableContainer.revalidate();
        productTableContainer.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JButton productAllBtn;
    private javax.swing.JButton productCancelBtn;
    private javax.swing.JButton productCreateBtn;
    private javax.swing.JPanel productHeaderContainer;
    private javax.swing.JTextField productIdTf;
    private javax.swing.JPanel productItemContainer;
    private javax.swing.JTextField productNameTf;
    private javax.swing.JButton productNewBtn;
    private javax.swing.JTextField productPriceTf;
    private javax.swing.JTextField productQuantityTf;
    private javax.swing.JButton productRemoveBtn;
    private javax.swing.JButton productResetBtn;
    private javax.swing.JButton productSearchBtn;
    private javax.swing.JTextField productSearchTf;
    private javax.swing.JTextField productSkuTf;
    private javax.swing.JComboBox<String> productSupplierComboBox;
    private javax.swing.JPanel productTab;
    private javax.swing.JTable productTable;
    private javax.swing.JPanel productTableContainer;
    private javax.swing.JButton productUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
